name: Build and Push Dev Image
on:
  push:
    branches:
      - dev

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Debug Docker Login
        run: |
          echo "Attempting to login with Docker Hub credentials..."
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_TOKEN=*****"  # Mask the token for safety
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }} || exit 1

      - name: Build Image
        run: docker image build -t ing2isimm2024/simplewebdev -f Dockerfile.dev .

      - name: Push Image
        run: docker image push ing2isimm2024/simplewebdev
