name: Build and Push Dev Image

on:
  push:
    branches:
      - dev

jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Image
        run: docker image build -t RamiIbrahim2002/simplewebdev -f Dockerfile.dev .

      - name: Push Image
        run: docker image push RamiIbrahim2002/simplewebdev
